### PR TITLE
feat: add `.zsh` extension on editer mode

### PR DESCRIPTION
**Pull request by shun-shobon**
for syntax highlighting

### CODE REVIEW

**Comment by jeffreytse** [comment]
Hi @shun-shobon 

Could you explain what does this change for?

Thanks and regards

**Comment by shun-shobon** [comment]
@jeffreytse

I noticed that the text editor that can be started with `vv` in normal mode does not have syntax highlighting for zsh.
So, I added a `.zsh` extension to the temp file used by the editor so that it can recognize the file type.

**Review by jeffreytse — COMMENTED** [review]
Why did you remove `mktemp` command?

**Comment by shun-shobon** [comment]
Because `mktemp` cannot specify a suffix.(`mktemp` can also dry-run with the `-u` option, but this is unsafe.)
So I used the process ID instead of `mktemp`.

**Comment by jeffreytse** [comment]
Thanks for the patch, I prefer to follow the file style of built-in widget `edit-command-line` (i.e. `/tmp/zshXXXXXX`). You can try it as below instructions.

```zsh
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd '!' edit-command-line
```

**Comment by shun-shobon** [comment]
I did not know about `edit-command-line`.
Thank you for giving me a better solution!

**Comment by jeffreytse** [comment]
Now this PR has been adjusted and merged, thank you for your contribution to syntax highlighting to make this plugin better. : )

**Pull request merged**
